platform :ios, '11.0'

target 'Plugin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Braintree'
  pod 'BraintreeDropIn'
  pod 'Braintree/PayPal'
  pod 'Braintree/Apple-Pay'
  pod 'Braintree/Venmo'
  pod 'Capacitor'
end

target 'PluginTests' do
  use_frameworks!

  pod 'Braintree'
  pod 'BraintreeDropIn'
  pod 'Braintree/PayPal'
  pod 'Braintree/Apple-Pay'
  pod 'Braintree/Venmo'
  pod 'Capacitor'
end
